# Generated by Django 4.2 on 2023-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesCounter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriescounter',
            name='calories',
            field=models.FloatField(max_length=200),
        ),
    ]
