# Generated by Django 4.2 on 2023-05-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesCounter', '0002_alter_caloriescounter_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriescounter',
            name='time',
            field=models.CharField(choices=[('Break fast', 'Break fast'), ('Lunch', 'Lunch'), ('Evening', 'Evening'), ('Dinner', 'Dinner')], default='Breakfast', max_length=200),
        ),
    ]
